version: "3.7"

services:
    service:
        image: zemoga_test-service
        env_file: .env
        build:
            target: builder
            context: .
        ports:
            - 18080:8080
            - 19090:9090
        volumes:
            - ./:/go/src/github.com/sail3/zemoga_test
            - swagger:/go/src/github.com/sail3/zemoga_test/swagger
            - ./oas/oas.yml:/go/src/github.com/sail3/zemoga_test/swagger/swagger.yml
        command: gowatch -p ./cmd/api
        depends_on:
            - swagger
            - db
        networks: 
            - default
    swagger:
        image: swaggerapi/swagger-ui:v3.23.10
        environment:
            URL: /swagger/swagger.yml
        volumes:
            - swagger:/usr/share/nginx/html
    db:
        image: postgres:13.5-alpine
        restart: always
        ports:
            - 15432:5432
        environment:
            POSTGRES_PASSWORD: 'zemoga_test'
            POSTGRES_USER: 'zemoga_test'
            POSTGRES_DB: 'zemoga_test_db'

volumes:
    # swagger named volume will be shared between service and swagger. So we can have a local swagger running
    swagger: null
